TEMPLATE = app
CONFIG -= console
CONFIG -= app_bundle
CONFIG -= qt

CONFIG += c++11

unix:LIBS += -lGLEW -lGL -lglfw
win32:LIBS += -lglew32s -lopengl32 -lglfw3

SOURCES += main.cpp \
    Core/Infra/singletonabs.cpp \
    Core/Infra/singletonmanager.cpp \
    Core/ObjectLevels/BaseLevel/baselevel.cpp \
    Core/ObjectLevels/GraphicLevel/graphiclevel.cpp \
    Core/ObjectLevels/PhysicLevel/physiclevel.cpp \
    Core/Infra/thread.cpp \
    Core/Infra/timer.cpp \
    Core/Infra/timermanager.cpp \
    Core/Main/scene.cpp \
    Core/ResourceLoader/modelloader.cpp \
    Core/Libs/glm/detail/dummy.cpp \
    Core/Libs/glm/detail/glm.cpp \
    Core/Libs/glew/glew.c \
    Core/ObjectLevels/object.cpp \
    Core/ResourceLoader/Loader/loader3ds.cpp \
    Core/ResourceLoader/Loader/loaderabs.cpp \
    Core/Libs/lib3ds/lib3ds_atmosphere.c \
    Core/Libs/lib3ds/lib3ds_background.c \
    Core/Libs/lib3ds/lib3ds_camera.c \
    Core/Libs/lib3ds/lib3ds_chunk.c \
    Core/Libs/lib3ds/lib3ds_chunktable.c \
    Core/Libs/lib3ds/lib3ds_file.c \
    Core/Libs/lib3ds/lib3ds_io.c \
    Core/Libs/lib3ds/lib3ds_light.c \
    Core/Libs/lib3ds/lib3ds_material.c \
    Core/Libs/lib3ds/lib3ds_math.c \
    Core/Libs/lib3ds/lib3ds_matrix.c \
    Core/Libs/lib3ds/lib3ds_mesh.c \
    Core/Libs/lib3ds/lib3ds_node.c \
    Core/Libs/lib3ds/lib3ds_quat.c \
    Core/Libs/lib3ds/lib3ds_shadow.c \
    Core/Libs/lib3ds/lib3ds_track.c \
    Core/Libs/lib3ds/lib3ds_util.c \
    Core/Libs/lib3ds/lib3ds_vector.c \
    Core/Libs/lib3ds/lib3ds_viewport.c \
    Core/engine.cpp \
    Core/Managers/scenemanager.cpp \
    Core/ObjectLevels/GraphicLevel/Shader/shader.cpp \
    Core/ObjectLevels/GraphicLevel/Shader/shaderprogramm.cpp \
    Core/Main/camera.cpp \
    Core/Managers/windowmanager.cpp \
    Core/Managers/keyboardmanager.cpp \
    Core/Main/button.cpp \
    Core/Managers/shadermanager.cpp \
    Core/Listeners/mouselistener.cpp \
    Core/Listeners/keyboardlistener.cpp \
    Core/Infra/threadregister.cpp \
    Core/Managers/texturemanager.cpp \
    Core/ObjectLevels/GraphicLevel/texture.cpp \
    Core/Libs/soil/image_DXT.c \
    Core/Libs/soil/image_helper.c \
    Core/Libs/soil/SOIL.c \
    Core/Libs/soil/stb_image_aug.c \
    Core/ResourceLoader/textureloader.cpp \
    Core/ResourceLoader/TextureLoaders/loaderjpeg.cpp \
    Core/ResourceLoader/TextureLoaders/textureloaderabs.cpp \
    Core/ResourceLoader/TextureLoaders/textureloaderbmp.cpp \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpheader.cpp \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfo.cpp \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfoheaderabs.cpp \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfoheadercore.cpp \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfoheaderv3.cpp \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfoheaderv4.cpp \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfoheaderv5.cpp \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpimage.cpp

HEADERS += \
    Core/Infra/preinfra.h \
    Core/Infra/singletonabs.h \
    Core/Infra/singleton.h \
    Core/Infra/singletonmanager.h \
    Core/ObjectLevels/BaseLevel/baselevel.h \
    Core/ObjectLevels/GraphicLevel/graphiclevel.h \
    Core/ObjectLevels/PhysicLevel/physiclevel.h \
    Core/Infra/thread.h \
    Core/Infra/timer.h \
    Core/Infra/timermanager.h \
    Core/Main/scene.h \
    Core/ResourceLoader/modelloader.h \
    Core/coreconfig.h \
    Core/Libs/glew/glew.h \
    Core/Libs/glew/glxew.h \
    Core/Libs/glew/wglew.h \
    Core/Libs/glfw/glfw3.h \
    Core/Libs/glfw/glfw3native.h \
    Core/Libs/glm/detail/_features.hpp \
    Core/Libs/glm/detail/_fixes.hpp \
    Core/Libs/glm/detail/_literals.hpp \
    Core/Libs/glm/detail/_noise.hpp \
    Core/Libs/glm/detail/_swizzle.hpp \
    Core/Libs/glm/detail/_swizzle_func.hpp \
    Core/Libs/glm/detail/_vectorize.hpp \
    Core/Libs/glm/detail/func_common.hpp \
    Core/Libs/glm/detail/func_exponential.hpp \
    Core/Libs/glm/detail/func_geometric.hpp \
    Core/Libs/glm/detail/func_integer.hpp \
    Core/Libs/glm/detail/func_matrix.hpp \
    Core/Libs/glm/detail/func_noise.hpp \
    Core/Libs/glm/detail/func_packing.hpp \
    Core/Libs/glm/detail/func_trigonometric.hpp \
    Core/Libs/glm/detail/func_vector_relational.hpp \
    Core/Libs/glm/detail/hint.hpp \
    Core/Libs/glm/detail/intrinsic_common.hpp \
    Core/Libs/glm/detail/intrinsic_exponential.hpp \
    Core/Libs/glm/detail/intrinsic_geometric.hpp \
    Core/Libs/glm/detail/intrinsic_integer.hpp \
    Core/Libs/glm/detail/intrinsic_matrix.hpp \
    Core/Libs/glm/detail/intrinsic_trigonometric.hpp \
    Core/Libs/glm/detail/intrinsic_vector_relational.hpp \
    Core/Libs/glm/detail/precision.hpp \
    Core/Libs/glm/detail/setup.hpp \
    Core/Libs/glm/detail/type_float.hpp \
    Core/Libs/glm/detail/type_gentype.hpp \
    Core/Libs/glm/detail/type_half.hpp \
    Core/Libs/glm/detail/type_int.hpp \
    Core/Libs/glm/detail/type_mat.hpp \
    Core/Libs/glm/detail/type_mat2x2.hpp \
    Core/Libs/glm/detail/type_mat2x3.hpp \
    Core/Libs/glm/detail/type_mat2x4.hpp \
    Core/Libs/glm/detail/type_mat3x2.hpp \
    Core/Libs/glm/detail/type_mat3x3.hpp \
    Core/Libs/glm/detail/type_mat3x4.hpp \
    Core/Libs/glm/detail/type_mat4x2.hpp \
    Core/Libs/glm/detail/type_mat4x3.hpp \
    Core/Libs/glm/detail/type_mat4x4.hpp \
    Core/Libs/glm/detail/type_vec.hpp \
    Core/Libs/glm/detail/type_vec1.hpp \
    Core/Libs/glm/detail/type_vec2.hpp \
    Core/Libs/glm/detail/type_vec3.hpp \
    Core/Libs/glm/detail/type_vec4.hpp \
    Core/Libs/glm/gtc/constants.hpp \
    Core/Libs/glm/gtc/epsilon.hpp \
    Core/Libs/glm/gtc/matrix_access.hpp \
    Core/Libs/glm/gtc/matrix_integer.hpp \
    Core/Libs/glm/gtc/matrix_inverse.hpp \
    Core/Libs/glm/gtc/matrix_transform.hpp \
    Core/Libs/glm/gtc/noise.hpp \
    Core/Libs/glm/gtc/packing.hpp \
    Core/Libs/glm/gtc/quaternion.hpp \
    Core/Libs/glm/gtc/random.hpp \
    Core/Libs/glm/gtc/reciprocal.hpp \
    Core/Libs/glm/gtc/type_precision.hpp \
    Core/Libs/glm/gtc/type_ptr.hpp \
    Core/Libs/glm/gtc/ulp.hpp \
    Core/Libs/glm/gtx/associated_min_max.hpp \
    Core/Libs/glm/gtx/bit.hpp \
    Core/Libs/glm/gtx/closest_point.hpp \
    Core/Libs/glm/gtx/color_space.hpp \
    Core/Libs/glm/gtx/color_space_YCoCg.hpp \
    Core/Libs/glm/gtx/compatibility.hpp \
    Core/Libs/glm/gtx/component_wise.hpp \
    Core/Libs/glm/gtx/constants.hpp \
    Core/Libs/glm/gtx/dual_quaternion.hpp \
    Core/Libs/glm/gtx/epsilon.hpp \
    Core/Libs/glm/gtx/euler_angles.hpp \
    Core/Libs/glm/gtx/extend.hpp \
    Core/Libs/glm/gtx/extented_min_max.hpp \
    Core/Libs/glm/gtx/fast_exponential.hpp \
    Core/Libs/glm/gtx/fast_square_root.hpp \
    Core/Libs/glm/gtx/fast_trigonometry.hpp \
    Core/Libs/glm/gtx/gradient_paint.hpp \
    Core/Libs/glm/gtx/handed_coordinate_space.hpp \
    Core/Libs/glm/gtx/inertia.hpp \
    Core/Libs/glm/gtx/int_10_10_10_2.hpp \
    Core/Libs/glm/gtx/integer.hpp \
    Core/Libs/glm/gtx/intersect.hpp \
    Core/Libs/glm/gtx/io.hpp \
    Core/Libs/glm/gtx/log_base.hpp \
    Core/Libs/glm/gtx/matrix_cross_product.hpp \
    Core/Libs/glm/gtx/matrix_interpolation.hpp \
    Core/Libs/glm/gtx/matrix_major_storage.hpp \
    Core/Libs/glm/gtx/matrix_operation.hpp \
    Core/Libs/glm/gtx/matrix_query.hpp \
    Core/Libs/glm/gtx/matrix_transform_2d.hpp \
    Core/Libs/glm/gtx/mixed_product.hpp \
    Core/Libs/glm/gtx/multiple.hpp \
    Core/Libs/glm/gtx/noise.hpp \
    Core/Libs/glm/gtx/norm.hpp \
    Core/Libs/glm/gtx/normal.hpp \
    Core/Libs/glm/gtx/normalize_dot.hpp \
    Core/Libs/glm/gtx/number_precision.hpp \
    Core/Libs/glm/gtx/optimum_pow.hpp \
    Core/Libs/glm/gtx/orthonormalize.hpp \
    Core/Libs/glm/gtx/perpendicular.hpp \
    Core/Libs/glm/gtx/polar_coordinates.hpp \
    Core/Libs/glm/gtx/projection.hpp \
    Core/Libs/glm/gtx/quaternion.hpp \
    Core/Libs/glm/gtx/random.hpp \
    Core/Libs/glm/gtx/raw_data.hpp \
    Core/Libs/glm/gtx/reciprocal.hpp \
    Core/Libs/glm/gtx/rotate_normalized_axis.hpp \
    Core/Libs/glm/gtx/rotate_vector.hpp \
    Core/Libs/glm/gtx/scalar_relational.hpp \
    Core/Libs/glm/gtx/simd_mat4.hpp \
    Core/Libs/glm/gtx/simd_quat.hpp \
    Core/Libs/glm/gtx/simd_vec4.hpp \
    Core/Libs/glm/gtx/spline.hpp \
    Core/Libs/glm/gtx/std_based_type.hpp \
    Core/Libs/glm/gtx/string_cast.hpp \
    Core/Libs/glm/gtx/transform.hpp \
    Core/Libs/glm/gtx/transform2.hpp \
    Core/Libs/glm/gtx/ulp.hpp \
    Core/Libs/glm/gtx/unsigned_int.hpp \
    Core/Libs/glm/gtx/vec1.hpp \
    Core/Libs/glm/gtx/vector_angle.hpp \
    Core/Libs/glm/gtx/vector_query.hpp \
    Core/Libs/glm/gtx/wrap.hpp \
    Core/Libs/glm/common.hpp \
    Core/Libs/glm/exponential.hpp \
    Core/Libs/glm/ext.hpp \
    Core/Libs/glm/fwd.hpp \
    Core/Libs/glm/geometric.hpp \
    Core/Libs/glm/glm.hpp \
    Core/Libs/glm/integer.hpp \
    Core/Libs/glm/mat2x2.hpp \
    Core/Libs/glm/mat2x3.hpp \
    Core/Libs/glm/mat2x4.hpp \
    Core/Libs/glm/mat3x2.hpp \
    Core/Libs/glm/mat3x3.hpp \
    Core/Libs/glm/mat3x4.hpp \
    Core/Libs/glm/mat4x2.hpp \
    Core/Libs/glm/mat4x3.hpp \
    Core/Libs/glm/mat4x4.hpp \
    Core/Libs/glm/matrix.hpp \
    Core/Libs/glm/packing.hpp \
    Core/Libs/glm/trigonometric.hpp \
    Core/Libs/glm/vec2.hpp \
    Core/Libs/glm/vec3.hpp \
    Core/Libs/glm/vec4.hpp \
    Core/Libs/glm/vector_relational.hpp \
    Core/ObjectLevels/object.h \
    Core/ResourceLoader/Loader/loader3ds.h \
    Core/ResourceLoader/Loader/loaderabs.h \
    Core/Libs/lib3ds/lib3ds.h \
    Core/Libs/lib3ds/lib3ds_impl.h \
    Core/engine.h \
    Core/Managers/scenemanager.h \
    Core/ObjectLevels/GraphicLevel/Shader/shader.h \
    Core/ObjectLevels/GraphicLevel/Shader/shaderprogramm.h \
    Core/ObjectLevels/GraphicLevel/pregraphic.h \
    Core/Main/camera.h \
    Core/Managers/windowmanager.h \
    Core/Managers/keyboardmanager.h \
    Core/Main/button.h \
    Core/Managers/shadermanager.h \
    Core/Listeners/mouselistener.h \
    Core/Listeners/keyboardlistener.h \
    Core/Infra/threadregister.h \
    Core/Infra/list.h \
    Core/Managers/texturemanager.h \
    Core/ObjectLevels/GraphicLevel/texture.h \
    Core/Libs/soil/image_DXT.h \
    Core/Libs/soil/image_helper.h \
    Core/Libs/soil/SOIL.h \
    Core/Libs/soil/stb_image_aug.h \
    Core/Libs/soil/stbi_DDS_aug.h \
    Core/Libs/soil/stbi_DDS_aug_c.h \
    Core/ResourceLoader/textureloader.h \
    Core/ResourceLoader/TextureLoaders/loaderjpeg.h \
    Core/ResourceLoader/TextureLoaders/textureloaderabs.h \
    Core/ResourceLoader/TextureLoaders/textureloaderbmp.h \
    Core/typedefs.h \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpheader.h \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfo.h \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfoheaderabs.h \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfoheadercore.h \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfoheaderv3.h \
    Core/Infra/utils.h \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfoheaderv4.h \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpinfoheaderv5.h \
    Core/ResourceLoader/TextureLoaders/BMP_Stack/bmpimage.h

OTHER_FILES += \
    Resources/Shaders/FragmentShader.fsh \
    Resources/Shaders/VertexShader.vsh \
    Resources/Models/Impreza/impreza_3ds.3ds \
    Resources/Models/Impreza/chasis.jpg \
    Resources/Models/Impreza/chasis_a.jpg \
    Resources/Models/Impreza/ruedas.jpg \
    Resources/Models/Impreza/ventanas.jpg \
    Resources/Models/Impreza_bmp/impreza_3ds.3ds \
    Resources/Models/Impreza_bmp/chasis.bmp \
    Resources/Models/Impreza_bmp/chasis_a.bmp \
    Resources/Models/Impreza_bmp/ruedas.bmp \
    Resources/Models/Impreza_bmp/ventanas.bmp \
    Core/Libs/glew/glew32s.lib \
    Core/Libs/glfw/glfw3.dll

