TEMPLATE = app
CONFIG -= app_bundle
CONFIG -= qt
CONFIG+=c++11
CONFIG += -static-libgcc

unix:LIBS += -lGLEW -lGL -lglfw

win32:LIBS += -lglew32s -lopengl32 -lglfw3
win32:HEADERS += System/glew/glew.h
win32:SOURCES += System/glew/glew.c


SOURCES += main.cpp \
    game.cpp \
    GraphicSystem/Shaders/shader.cpp \
    GraphicSystem/Shaders/shaderprogram.cpp \
    GraphicSystem/graphicobject.cpp \
    GraphicSystem/Shaders/shadermanager.cpp \
    Main/scenemanager.cpp \
    Main/object.cpp \
    Common/objectraw.cpp \
    Utils/objectloader.cpp \
    Utils/ObjectLoaders/loader3ds.cpp \
    Utils/ObjectLoaders/loaderabs.cpp \
    System/windowmanager.cpp \
    Main/scene.cpp \
    Main/camera.cpp \
    Utils/ObjectLoaders/3ds/lib3ds_atmosphere.c \
    Utils/ObjectLoaders/3ds/lib3ds_background.c \
    Utils/ObjectLoaders/3ds/lib3ds_camera.c \
    Utils/ObjectLoaders/3ds/lib3ds_chunk.c \
    Utils/ObjectLoaders/3ds/lib3ds_chunktable.c \
    Utils/ObjectLoaders/3ds/lib3ds_file.c \
    Utils/ObjectLoaders/3ds/lib3ds_io.c \
    Utils/ObjectLoaders/3ds/lib3ds_light.c \
    Utils/ObjectLoaders/3ds/lib3ds_material.c \
    Utils/ObjectLoaders/3ds/lib3ds_math.c \
    Utils/ObjectLoaders/3ds/lib3ds_matrix.c \
    Utils/ObjectLoaders/3ds/lib3ds_mesh.c \
    Utils/ObjectLoaders/3ds/lib3ds_node.c \
    Utils/ObjectLoaders/3ds/lib3ds_quat.c \
    Utils/ObjectLoaders/3ds/lib3ds_shadow.c \
    Utils/ObjectLoaders/3ds/lib3ds_track.c \
    Utils/ObjectLoaders/3ds/lib3ds_util.c \
    Utils/ObjectLoaders/3ds/lib3ds_vector.c \
    Utils/ObjectLoaders/3ds/lib3ds_viewport.c \
    GraphicSystem/Testure/texture.cpp \
    Utils/imageloader.cpp \
    Utils/ImageLoaders/imageloaderabs.cpp \
    Utils/ImageLoaders/loaderjpeg.cpp \
    Utils/ImageLoaders/soil/image_DXT.c \
    Utils/ImageLoaders/soil/image_helper.c \
    Utils/ImageLoaders/soil/SOIL.c \
    Utils/ImageLoaders/soil/stb_image_aug.c \
    System/keyboardmanager.cpp \
    Main/keylistener.cpp \
    Infra/timer.cpp \
    Infra/timermanager.cpp \
    System/glm/detail/dummy.cpp \
    System/glm/detail/glm.cpp \
    Infra/singletonmanager.cpp \
    Infra/singletonabs.cpp \
    PhysicSystem/physicobject.cpp \
    PhysicSystem/BulletPhysic/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.cpp \
    PhysicSystem/BulletPhysic/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.cpp \
    PhysicSystem/BulletPhysic/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.cpp \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.cpp \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.cpp \
    PhysicSystem/BulletPhysic/Bullet3Common/b3AlignedAllocator.cpp \
    PhysicSystem/BulletPhysic/Bullet3Common/b3Logging.cpp \
    PhysicSystem/BulletPhysic/Bullet3Common/b3Vector3.cpp \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.cpp \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.cpp \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.cpp \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.cpp \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.cpp \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/b3CpuRigidBodyPipeline.cpp \
    PhysicSystem/BulletPhysic/Bullet3Geometry/b3ConvexHullComputer.cpp \
    PhysicSystem/BulletPhysic/Bullet3Geometry/b3GeometryUtil.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/b3GpuGridBroadphase.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvh.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvhBroadphase.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/b3GpuSapBroadphase.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/Initialize/b3OpenCLUtils.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3ContactCache.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3ConvexHullContact.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3GjkEpa.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3GjkPairDetector.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3OptimizedBvh.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3QuantizedBvh.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3StridingMeshInterface.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3TriangleCallback.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3TriangleIndexVertexArray.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3VoronoiSimplexSolver.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3BoundSearchCL.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3FillCL.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3LauncherCL.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanCL.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanFloat4CL.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3RadixSort32CL.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/Raycast/b3GpuRaycast.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuGenericConstraint.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuJacobiContactSolver.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuNarrowPhase.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuPgsConstraintSolver.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuPgsContactSolver.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipeline.cpp \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3Solver.cpp \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.cpp \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3Chunk.cpp \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3DNA.cpp \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3File.cpp \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3Serializer.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btAxisSweep3.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btDbvt.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btDispatcher.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionObject.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionWorld.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionWorldImporter.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btGhostObject.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btManifoldResult.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btUnionFind.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btBox2dShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btBoxShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btCapsuleShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btCollisionShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btCompoundShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConcaveShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConeShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvex2dShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexHullShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexInternalShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexPolyhedron.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btCylinderShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btEmptyShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btMultiSphereShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btOptimizedBvh.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btShapeHull.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btSphereShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btStaticPlaneShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btStridingMeshInterface.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTetrahedronShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleBuffer.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleCallback.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleMesh.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleMeshShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btUniformScalingShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btContactProcessing.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGenericPoolAllocator.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGImpactBvh.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGImpactShape.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btTriangleShapeEx.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_box_set.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_contact.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_memory.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_tri_collision.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btConvexCast.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Character/btKinematicCharacterController.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btContactConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btFixedConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btGearConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btHingeConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btSliderConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btTypedConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Dynamics/btRigidBody.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBody.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyJointMotor.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyPoint2Point.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btDantzigLCP.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btMLCPSolver.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Vehicle/btRaycastVehicle.cpp \
    PhysicSystem/BulletPhysic/BulletDynamics/Vehicle/btWheelInfo.cpp \
    PhysicSystem/BulletPhysic/BulletSoftBody/btDefaultSoftBodySolver.cpp \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBody.cpp \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBodyHelpers.cpp \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.cpp \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftRigidCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftRigidDynamicsWorld.cpp \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftSoftCollisionAlgorithm.cpp \
    PhysicSystem/BulletPhysic/LinearMath/btAlignedAllocator.cpp \
    PhysicSystem/BulletPhysic/LinearMath/btConvexHull.cpp \
    PhysicSystem/BulletPhysic/LinearMath/btConvexHullComputer.cpp \
    PhysicSystem/BulletPhysic/LinearMath/btGeometryUtil.cpp \
    PhysicSystem/BulletPhysic/LinearMath/btPolarDecomposition.cpp \
    PhysicSystem/BulletPhysic/LinearMath/btQuickprof.cpp \
    PhysicSystem/BulletPhysic/LinearMath/btSerializer.cpp \
    PhysicSystem/BulletPhysic/LinearMath/btVector3.cpp \
    PhysicSystem/BulletPhysic/clew/clew.c

HEADERS += \
    game.h \
    Common/precommon.h \
    GraphicSystem/pregraphic.h \
    GraphicSystem/Shaders/shader.h \
    GraphicSystem/Shaders/shaderprogram.h \
    GraphicSystem/graphicobject.h \
    GraphicSystem/Shaders/shadermanager.h \
    Main/scenemanager.h \
    Main/premain.h \
    Main/object.h \
    Common/objectraw.h \
    Utils/objectloader.h \
    Utils/ObjectLoaders/loader3ds.h \
    Utils/ObjectLoaders/loaderabs.h \
    System/windowmanager.h \
    Main/scene.h \
    Main/camera.h \
    Utils/ObjectLoaders/3ds/lib3ds.h \
    Utils/ObjectLoaders/3ds/lib3ds_impl.h \
    GraphicSystem/Testure/texture.h \
    Utils/imageloader.h \
    Utils/ImageLoaders/imageloaderabs.h \
    Utils/ImageLoaders/loaderjpeg.h \
    Utils/ImageLoaders/soil/image_DXT.h \
    Utils/ImageLoaders/soil/image_helper.h \
    Utils/ImageLoaders/soil/SOIL.h \
    Utils/ImageLoaders/soil/stb_image_aug.h \
    Utils/ImageLoaders/soil/stbi_DDS_aug.h \
    Utils/ImageLoaders/soil/stbi_DDS_aug_c.h \
    System/keyboardmanager.h \
    Main/keylistener.h \
    Infra/singleton.h \
    Infra/timer.h \
    Infra/timermanager.h \
    System/glew/wglew.h \
    System/glm/detail/_features.hpp \
    System/glm/detail/_fixes.hpp \
    System/glm/detail/_literals.hpp \
    System/glm/detail/_noise.hpp \
    System/glm/detail/_swizzle.hpp \
    System/glm/detail/_swizzle_func.hpp \
    System/glm/detail/_vectorize.hpp \
    System/glm/detail/func_common.hpp \
    System/glm/detail/func_exponential.hpp \
    System/glm/detail/func_geometric.hpp \
    System/glm/detail/func_integer.hpp \
    System/glm/detail/func_matrix.hpp \
    System/glm/detail/func_noise.hpp \
    System/glm/detail/func_packing.hpp \
    System/glm/detail/func_trigonometric.hpp \
    System/glm/detail/func_vector_relational.hpp \
    System/glm/detail/hint.hpp \
    System/glm/detail/intrinsic_common.hpp \
    System/glm/detail/intrinsic_exponential.hpp \
    System/glm/detail/intrinsic_geometric.hpp \
    System/glm/detail/intrinsic_integer.hpp \
    System/glm/detail/intrinsic_matrix.hpp \
    System/glm/detail/intrinsic_trigonometric.hpp \
    System/glm/detail/intrinsic_vector_relational.hpp \
    System/glm/detail/precision.hpp \
    System/glm/detail/setup.hpp \
    System/glm/detail/type_float.hpp \
    System/glm/detail/type_gentype.hpp \
    System/glm/detail/type_half.hpp \
    System/glm/detail/type_int.hpp \
    System/glm/detail/type_mat.hpp \
    System/glm/detail/type_mat2x2.hpp \
    System/glm/detail/type_mat2x3.hpp \
    System/glm/detail/type_mat2x4.hpp \
    System/glm/detail/type_mat3x2.hpp \
    System/glm/detail/type_mat3x3.hpp \
    System/glm/detail/type_mat3x4.hpp \
    System/glm/detail/type_mat4x2.hpp \
    System/glm/detail/type_mat4x3.hpp \
    System/glm/detail/type_mat4x4.hpp \
    System/glm/detail/type_vec.hpp \
    System/glm/detail/type_vec1.hpp \
    System/glm/detail/type_vec2.hpp \
    System/glm/detail/type_vec3.hpp \
    System/glm/detail/type_vec4.hpp \
    System/glm/gtc/constants.hpp \
    System/glm/gtc/epsilon.hpp \
    System/glm/gtc/matrix_access.hpp \
    System/glm/gtc/matrix_integer.hpp \
    System/glm/gtc/matrix_inverse.hpp \
    System/glm/gtc/matrix_transform.hpp \
    System/glm/gtc/noise.hpp \
    System/glm/gtc/packing.hpp \
    System/glm/gtc/quaternion.hpp \
    System/glm/gtc/random.hpp \
    System/glm/gtc/reciprocal.hpp \
    System/glm/gtc/type_precision.hpp \
    System/glm/gtc/type_ptr.hpp \
    System/glm/gtc/ulp.hpp \
    System/glm/gtx/associated_min_max.hpp \
    System/glm/gtx/bit.hpp \
    System/glm/gtx/closest_point.hpp \
    System/glm/gtx/color_space.hpp \
    System/glm/gtx/color_space_YCoCg.hpp \
    System/glm/gtx/compatibility.hpp \
    System/glm/gtx/component_wise.hpp \
    System/glm/gtx/constants.hpp \
    System/glm/gtx/dual_quaternion.hpp \
    System/glm/gtx/epsilon.hpp \
    System/glm/gtx/euler_angles.hpp \
    System/glm/gtx/extend.hpp \
    System/glm/gtx/extented_min_max.hpp \
    System/glm/gtx/fast_exponential.hpp \
    System/glm/gtx/fast_square_root.hpp \
    System/glm/gtx/fast_trigonometry.hpp \
    System/glm/gtx/gradient_paint.hpp \
    System/glm/gtx/handed_coordinate_space.hpp \
    System/glm/gtx/inertia.hpp \
    System/glm/gtx/int_10_10_10_2.hpp \
    System/glm/gtx/integer.hpp \
    System/glm/gtx/intersect.hpp \
    System/glm/gtx/io.hpp \
    System/glm/gtx/log_base.hpp \
    System/glm/gtx/matrix_cross_product.hpp \
    System/glm/gtx/matrix_interpolation.hpp \
    System/glm/gtx/matrix_major_storage.hpp \
    System/glm/gtx/matrix_operation.hpp \
    System/glm/gtx/matrix_query.hpp \
    System/glm/gtx/matrix_transform_2d.hpp \
    System/glm/gtx/mixed_product.hpp \
    System/glm/gtx/multiple.hpp \
    System/glm/gtx/noise.hpp \
    System/glm/gtx/norm.hpp \
    System/glm/gtx/normal.hpp \
    System/glm/gtx/normalize_dot.hpp \
    System/glm/gtx/number_precision.hpp \
    System/glm/gtx/optimum_pow.hpp \
    System/glm/gtx/orthonormalize.hpp \
    System/glm/gtx/perpendicular.hpp \
    System/glm/gtx/polar_coordinates.hpp \
    System/glm/gtx/projection.hpp \
    System/glm/gtx/quaternion.hpp \
    System/glm/gtx/random.hpp \
    System/glm/gtx/raw_data.hpp \
    System/glm/gtx/reciprocal.hpp \
    System/glm/gtx/rotate_normalized_axis.hpp \
    System/glm/gtx/rotate_vector.hpp \
    System/glm/gtx/scalar_relational.hpp \
    System/glm/gtx/simd_mat4.hpp \
    System/glm/gtx/simd_quat.hpp \
    System/glm/gtx/simd_vec4.hpp \
    System/glm/gtx/spline.hpp \
    System/glm/gtx/std_based_type.hpp \
    System/glm/gtx/string_cast.hpp \
    System/glm/gtx/transform.hpp \
    System/glm/gtx/transform2.hpp \
    System/glm/gtx/ulp.hpp \
    System/glm/gtx/unsigned_int.hpp \
    System/glm/gtx/vec1.hpp \
    System/glm/gtx/vector_angle.hpp \
    System/glm/gtx/vector_query.hpp \
    System/glm/gtx/wrap.hpp \
    System/glm/common.hpp \
    System/glm/exponential.hpp \
    System/glm/ext.hpp \
    System/glm/fwd.hpp \
    System/glm/geometric.hpp \
    System/glm/glm.hpp \
    System/glm/integer.hpp \
    System/glm/mat2x2.hpp \
    System/glm/mat2x3.hpp \
    System/glm/mat2x4.hpp \
    System/glm/mat3x2.hpp \
    System/glm/mat3x3.hpp \
    System/glm/mat3x4.hpp \
    System/glm/mat4x2.hpp \
    System/glm/mat4x3.hpp \
    System/glm/mat4x4.hpp \
    System/glm/matrix.hpp \
    System/glm/packing.hpp \
    System/glm/trigonometric.hpp \
    System/glm/vec2.hpp \
    System/glm/vec3.hpp \
    System/glm/vec4.hpp \
    System/glm/vector_relational.hpp \
    System/glfw/glfw3.h \
    System/glfw/glfw3native.h \
    Infra/singletonmanager.h \
    Infra/singletonabs.h \
    PhysicSystem/physicobject.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/BroadPhaseCollision/shared/b3Aabb.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/BroadPhaseCollision/b3BroadphaseCallback.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/BroadPhaseCollision/b3DynamicBvh.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/BroadPhaseCollision/b3DynamicBvhBroadphase.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/BroadPhaseCollision/b3OverlappingPair.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/BroadPhaseCollision/b3OverlappingPairCache.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhSubtreeInfoData.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3BvhTraversal.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3ClipFaces.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3Collidable.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3Contact4Data.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactConvexConvexSAT.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3ContactSphereSphere.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3ConvexPolyhedronData.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3FindConcaveSatAxis.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3FindSeparatingAxis.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3MprPenetration.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3NewContactReduction.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3QuantizedBvhNodeData.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3ReduceContacts.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3RigidBodyData.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/shared/b3UpdateAabbs.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/b3Config.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/b3Contact4.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/b3ConvexUtility.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/b3CpuNarrowPhase.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/b3RaycastInfo.h \
    PhysicSystem/BulletPhysic/Bullet3Collision/NarrowPhaseCollision/b3RigidBodyCL.h \
    PhysicSystem/BulletPhysic/Bullet3Common/shared/b3Float4.h \
    PhysicSystem/BulletPhysic/Bullet3Common/shared/b3Int2.h \
    PhysicSystem/BulletPhysic/Bullet3Common/shared/b3Int4.h \
    PhysicSystem/BulletPhysic/Bullet3Common/shared/b3Mat3x3.h \
    PhysicSystem/BulletPhysic/Bullet3Common/shared/b3PlatformDefinitions.h \
    PhysicSystem/BulletPhysic/Bullet3Common/shared/b3Quat.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3AlignedAllocator.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3AlignedObjectArray.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3CommandLineArgs.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3FileUtils.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3HashMap.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3Logging.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3Matrix3x3.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3MinMax.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3PoolAllocator.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3QuadWord.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3Quaternion.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3Random.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3Scalar.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3StackAlloc.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3Transform.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3TransformUtil.h \
    PhysicSystem/BulletPhysic/Bullet3Common/b3Vector3.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3ContactSolverInfo.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3FixedConstraint.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3Generic6DofConstraint.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3JacobianEntry.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3PgsJacobiSolver.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3Point2PointConstraint.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3SolverBody.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3SolverConstraint.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/ConstraintSolver/b3TypedConstraint.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/shared/b3ContactConstraint4.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/shared/b3ConvertConstraint4.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/shared/b3Inertia.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/shared/b3IntegrateTransforms.h \
    PhysicSystem/BulletPhysic/Bullet3Dynamics/b3CpuRigidBodyPipeline.h \
    PhysicSystem/BulletPhysic/Bullet3Geometry/b3AabbUtil.h \
    PhysicSystem/BulletPhysic/Bullet3Geometry/b3ConvexHullComputer.h \
    PhysicSystem/BulletPhysic/Bullet3Geometry/b3GeometryUtil.h \
    PhysicSystem/BulletPhysic/Bullet3Geometry/b3GrahamScan2dConvexHull.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/kernels/gridBroadphaseKernels.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/kernels/parallelLinearBvhKernels.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/kernels/sapKernels.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/b3GpuBroadphaseInterface.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/b3GpuGridBroadphase.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvh.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/b3GpuParallelLinearBvhBroadphase.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/b3GpuSapBroadphase.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/BroadphaseCollision/b3SapAabb.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/Initialize/b3OpenCLInclude.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/Initialize/b3OpenCLUtils.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/kernels/bvhTraversal.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/kernels/mprKernels.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/kernels/primitiveContacts.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/kernels/satClipHullContacts.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/kernels/satConcaveKernels.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/kernels/satKernels.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3BvhInfo.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3ContactCache.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3ConvexHullContact.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3ConvexPolyhedronCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3GjkEpa.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3GjkPairDetector.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3OptimizedBvh.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3QuantizedBvh.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3StridingMeshInterface.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3SupportMappings.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3TriangleCallback.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3TriangleIndexVertexArray.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3VectorFloat4.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/NarrowphaseCollision/b3VoronoiSimplexSolver.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/kernels/BoundSearchKernelsCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/kernels/CopyKernelsCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/kernels/FillKernelsCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanKernelsCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/kernels/PrefixScanKernelsFloat4CL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/kernels/RadixSort32KernelsCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3BoundSearchCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3BufferInfoCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3FillCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3LauncherCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3OpenCLArray.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanCL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3PrefixScanFloat4CL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/ParallelPrimitives/b3RadixSort32CL.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/Raycast/kernels/rayCastKernels.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/Raycast/b3GpuRaycast.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/kernels/batchingKernels.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/kernels/batchingKernelsNew.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/kernels/integrateKernel.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/kernels/jointSolver.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/kernels/solveContact.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/kernels/solveFriction.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/kernels/solverSetup.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/kernels/solverSetup2.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/kernels/solverUtils.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/kernels/updateAabbsKernel.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuConstraint4.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuGenericConstraint.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuJacobiContactSolver.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuNarrowPhase.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuNarrowPhaseInternalData.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuPgsConstraintSolver.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuPgsContactSolver.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipeline.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuRigidBodyPipelineInternalData.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuSolverBody.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3GpuSolverConstraint.h \
    PhysicSystem/BulletPhysic/Bullet3OpenCL/RigidBody/b3Solver.h \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/autogenerated/bullet2.h \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3BulletFile.h \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3Chunk.h \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3Common.h \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3Defines.h \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3DNA.h \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3File.h \
    PhysicSystem/BulletPhysic/Bullet3Serialize/Bullet2FileLoader/b3Serializer.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btAxisSweep3.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btBroadphaseInterface.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btBroadphaseProxy.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btDbvt.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btDbvtBroadphase.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btDispatcher.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btMultiSapBroadphase.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btOverlappingPairCache.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btOverlappingPairCallback.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btQuantizedBvh.h \
    PhysicSystem/BulletPhysic/BulletCollision/BroadphaseCollision/btSimpleBroadphase.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btBoxBoxDetector.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionConfiguration.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionCreateFunc.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionDispatcher.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionObject.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionObjectWrapper.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionWorld.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCollisionWorldImporter.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btGhostObject.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btHashedSimplePairCache.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btInternalEdgeUtility.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btManifoldResult.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btSimulationIslandManager.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/btUnionFind.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionDispatch/SphereTriangleDetector.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btBox2dShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btBoxShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btBvhTriangleMeshShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btCapsuleShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btCollisionMargin.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btCollisionShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btCompoundShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConcaveShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConeShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvex2dShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexHullShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexInternalShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexPointCloudShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexPolyhedron.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btConvexTriangleMeshShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btCylinderShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btEmptyShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btMaterial.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btMinkowskiSumShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btMultiSphereShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btOptimizedBvh.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btPolyhedralConvexShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btShapeHull.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btSphereShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btStaticPlaneShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btStridingMeshInterface.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTetrahedronShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleBuffer.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleCallback.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleIndexVertexArray.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleInfoMap.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleMesh.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleMeshShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btTriangleShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/CollisionShapes/btUniformScalingShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btBoxCollision.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btClipPolygon.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btCompoundFromGimpact.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btContactProcessing.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGenericPoolAllocator.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGeometryOperations.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGImpactBvh.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGImpactCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGImpactMassUtil.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGImpactQuantizedBvh.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btGImpactShape.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btQuantization.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/btTriangleShapeEx.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_array.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_basic_geometry_operations.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_bitset.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_box_collision.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_box_set.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_clip_polygon.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_contact.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_geom_types.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_geometry.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_hash_table.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_linear_math.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_math.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_memory.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_radixsort.h \
    PhysicSystem/BulletPhysic/BulletCollision/Gimpact/gim_tri_collision.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btComputeGjkEpaPenetration.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btConvexCast.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btConvexPenetrationDepthSolver.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btDiscreteCollisionDetectorInterface.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btGjkCollisionDescription.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btGjkConvexCast.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btGjkEpa2.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btGjkEpa3.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btManifoldPoint.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btMprPenetration.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btPersistentManifold.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btPointCollector.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btRaycastCallback.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btSimplexSolverInterface.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.h \
    PhysicSystem/BulletPhysic/BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Character/btCharacterControllerInterface.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Character/btKinematicCharacterController.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btConeTwistConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btConstraintSolver.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btContactConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btContactSolverInfo.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btFixedConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btGearConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btGeneric6DofSpring2Constraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btHinge2Constraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btHingeConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btJacobianEntry.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btPoint2PointConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btSliderConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btSolverBody.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btSolverConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btTypedConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/ConstraintSolver/btUniversalConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Dynamics/btActionInterface.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Dynamics/btDynamicsWorld.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Dynamics/btRigidBody.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Dynamics/btSimpleDynamicsWorld.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBody.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyConstraintSolver.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyJointMotor.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyLink.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyLinkCollider.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodyPoint2Point.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Featherstone/btMultiBodySolverConstraint.h \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btDantzigLCP.h \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btDantzigSolver.h \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btLemkeAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btLemkeSolver.h \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btMLCPSolver.h \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btMLCPSolverInterface.h \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btPATHSolver.h \
    PhysicSystem/BulletPhysic/BulletDynamics/MLCPSolvers/btSolveProjectedGaussSeidel.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Vehicle/btRaycastVehicle.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Vehicle/btVehicleRaycaster.h \
    PhysicSystem/BulletPhysic/BulletDynamics/Vehicle/btWheelInfo.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btDefaultSoftBodySolver.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBody.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBodyData.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBodyHelpers.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBodyInternals.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBodySolvers.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftBodySolverVertexBuffer.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftRigidCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftRigidDynamicsWorld.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSoftSoftCollisionAlgorithm.h \
    PhysicSystem/BulletPhysic/BulletSoftBody/btSparseSDF.h \
    PhysicSystem/BulletPhysic/clew/clew.h \
    PhysicSystem/BulletPhysic/LinearMath/btAabbUtil2.h \
    PhysicSystem/BulletPhysic/LinearMath/btAlignedAllocator.h \
    PhysicSystem/BulletPhysic/LinearMath/btAlignedObjectArray.h \
    PhysicSystem/BulletPhysic/LinearMath/btConvexHull.h \
    PhysicSystem/BulletPhysic/LinearMath/btConvexHullComputer.h \
    PhysicSystem/BulletPhysic/LinearMath/btCpuFeatureUtility.h \
    PhysicSystem/BulletPhysic/LinearMath/btDefaultMotionState.h \
    PhysicSystem/BulletPhysic/LinearMath/btGeometryUtil.h \
    PhysicSystem/BulletPhysic/LinearMath/btGrahamScan2dConvexHull.h \
    PhysicSystem/BulletPhysic/LinearMath/btHashMap.h \
    PhysicSystem/BulletPhysic/LinearMath/btIDebugDraw.h \
    PhysicSystem/BulletPhysic/LinearMath/btList.h \
    PhysicSystem/BulletPhysic/LinearMath/btMatrix3x3.h \
    PhysicSystem/BulletPhysic/LinearMath/btMatrixX.h \
    PhysicSystem/BulletPhysic/LinearMath/btMinMax.h \
    PhysicSystem/BulletPhysic/LinearMath/btMotionState.h \
    PhysicSystem/BulletPhysic/LinearMath/btPolarDecomposition.h \
    PhysicSystem/BulletPhysic/LinearMath/btPoolAllocator.h \
    PhysicSystem/BulletPhysic/LinearMath/btQuadWord.h \
    PhysicSystem/BulletPhysic/LinearMath/btQuaternion.h \
    PhysicSystem/BulletPhysic/LinearMath/btQuickprof.h \
    PhysicSystem/BulletPhysic/LinearMath/btRandom.h \
    PhysicSystem/BulletPhysic/LinearMath/btScalar.h \
    PhysicSystem/BulletPhysic/LinearMath/btSerializer.h \
    PhysicSystem/BulletPhysic/LinearMath/btStackAlloc.h \
    PhysicSystem/BulletPhysic/LinearMath/btTransform.h \
    PhysicSystem/BulletPhysic/LinearMath/btTransformUtil.h \
    PhysicSystem/BulletPhysic/LinearMath/btVector3.h \
    PhysicSystem/BulletPhysic/btBulletCollisionCommon.h \
    PhysicSystem/BulletPhysic/btBulletDynamicsCommon.h \
    PhysicSystem/prephysic.h \
    PhysicSystem/openclconfig.h

OTHER_FILES += \
    Resources/Menus/MainMenu.bmp \
    Resources/Shaders/FragmentShader.fsh \
    Resources/Shaders/VertexShader.vsh \
    Resources/Engine.3ds \
    Config.txt \
    Resources/Fonts/Arial.bmp \
    System/glfw/glfw3.a \
    System/glfw/glfw3.dll
